#!/usr/bin/env python3
"""
Post-process a CycloneDX SBOM generated by `cyclonedx-py environment ...`
for this plugin:

1. Add this plugin's own component metadata. cyclonedx-py only sees the
   *installed dependencies* of the environment it's pointed at; it has no
   idea this venv exists to support one particular application, so the SBOM
   it produces has no root/"metadata.component" entry identifying
   dicom_anonymize itself.
2. Strip the `pip` component. `python -m venv` bootstraps a `pip` into
   every venv it creates; it's build tooling, not a runtime dependency this
   plugin ships or depends on, and showing up in the SBOM anyway.

Usage: finalize_sbom.py <sbom.cdx.json> <plugin_version>
"""
import json
import sys


def main():
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <sbom.cdx.json> <plugin_version>", file=sys.stderr)
        sys.exit(2)

    sbom_path, version = sys.argv[1], sys.argv[2]

    with open(sbom_path) as f:
        sbom = json.load(f)

    # `pip` is bootstrapped into every venv by `python -m venv`; it isn't a
    # runtime dependency this plugin ships or depends on, just build
    # tooling that happened to be present in the venv being scanned.
    sbom["components"] = [
        c for c in sbom.get("components", []) if c.get("name") != "pip"
    ]

    sbom["metadata"]["component"] = {
        "type": "application",
        "name": "dicom_anonymize",
        "version": version,
        "description": "A ChRIS ds plugin that recursively de-identifies DICOM datasets",
        "purl": f"pkg:github/FNNDSC/pl-dicom_anonymize@{version}",
    }

    with open(sbom_path, "w") as f:
        json.dump(sbom, f, indent=2)


if __name__ == "__main__":
    main()
